version: '3'
services:
  postgres:
    image: postgres:14
    container_name: gps-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gps_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
